/** ccTLD and common second-level domain → ISO 3166-1 alpha-2 */
const COMPOUND_TLD_TO_ISO: Record<string, string> = {
  "co.uk": "GB",
  "org.uk": "GB",
  "ac.uk": "GB",
  "gov.uk": "GB",
  "com.au": "AU",
  "net.au": "AU",
  "org.au": "AU",
  "edu.au": "AU",
  "co.in": "IN",
  "net.in": "IN",
  "org.in": "IN",
  "firm.in": "IN",
  "gen.in": "IN",
  "com.br": "BR",
  "net.br": "BR",
  "org.br": "BR",
  "co.za": "ZA",
  "org.za": "ZA",
  "com.mx": "MX",
  "com.sg": "SG",
  "com.hk": "HK",
  "co.jp": "JP",
  "ne.jp": "JP",
  "or.jp": "JP",
  "co.nz": "NZ",
  "com.ar": "AR",
  "com.tr": "TR",
  "co.kr": "KR",
  "com.cn": "CN",
  "com.tw": "TW",
  "com.my": "MY",
  "co.id": "ID",
  "com.ph": "PH",
  "com.vn": "VN",
  "com.pk": "PK",
  "com.bd": "BD",
  "com.ng": "NG",
  "com.eg": "EG",
  "co.il": "IL",
  "org.il": "IL",
  "com.sa": "SA",
  "com.ae": "AE",
  "co.th": "TH",
  "com.co": "CO",
  "com.pe": "PE",
  "com.cl": "CL",
  "com.pl": "PL",
  "com.es": "ES",
  "com.fr": "FR",
  "com.de": "DE",
  "com.it": "IT",
  "com.nl": "NL",
  "com.be": "BE",
  "com.ch": "CH",
  "com.at": "AT",
  "com.se": "SE",
  "com.no": "NO",
  "com.dk": "DK",
  "com.fi": "FI",
  "com.pt": "PT",
  "com.gr": "GR",
  "com.ro": "RO",
  "com.hu": "HU",
  "com.cz": "CZ",
  "com.sk": "SK",
  "com.ua": "UA",
  "com.ru": "RU",
  "com.ca": "CA",
  "com.us": "US",
  "edu.in": "IN",
  "ac.in": "IN",
  "gov.in": "IN",
};

const SINGLE_TLD_TO_ISO: Record<string, string> = {
  in: "IN",
  uk: "GB",
  de: "DE",
  fr: "FR",
  au: "AU",
  ca: "CA",
  jp: "JP",
  cn: "CN",
  br: "BR",
  mx: "MX",
  sg: "SG",
  ae: "AE",
  sa: "SA",
  za: "ZA",
  nl: "NL",
  es: "ES",
  it: "IT",
  ru: "RU",
  kr: "KR",
  nz: "NZ",
  ie: "IE",
  ch: "CH",
  se: "SE",
  no: "NO",
  dk: "DK",
  fi: "FI",
  pl: "PL",
  pt: "PT",
  be: "BE",
  at: "AT",
  hk: "HK",
  tw: "TW",
  my: "MY",
  th: "TH",
  ph: "PH",
  id: "ID",
  vn: "VN",
  pk: "PK",
  bd: "BD",
  lk: "LK",
  np: "NP",
  ng: "NG",
  ke: "KE",
  eg: "EG",
  il: "IL",
  tr: "TR",
  ar: "AR",
  cl: "CL",
  co: "CO",
  pe: "PE",
  gr: "GR",
  ro: "RO",
  hu: "HU",
  cz: "CZ",
  sk: "SK",
  ua: "UA",
  us: "US",
  ir: "IR",
  iq: "IQ",
  kw: "KW",
  qa: "QA",
  om: "OM",
  bh: "BH",
  jo: "JO",
  lb: "LB",
  gh: "GH",
  tz: "TZ",
  ug: "UG",
  zm: "ZM",
  zw: "ZW",
  mu: "MU",
  ma: "MA",
  tn: "TN",
  dz: "DZ",
  et: "ET",
  sn: "SN",
  cm: "CM",
  ao: "AO",
  mz: "MZ",
  uy: "UY",
  py: "PY",
  bo: "BO",
  ec: "EC",
  ve: "VE",
  pa: "PA",
  cr: "CR",
  gt: "GT",
  hn: "HN",
  sv: "SV",
  ni: "NI",
  do: "DO",
  jm: "JM",
  tt: "TT",
  bb: "BB",
  bs: "BS",
  cy: "CY",
  mt: "MT",
  lu: "LU",
  is: "IS",
  lv: "LV",
  lt: "LT",
  ee: "EE",
  by: "BY",
  kz: "KZ",
  uz: "UZ",
  ge: "GE",
  am: "AM",
  az: "AZ",
  kg: "KG",
  tj: "TJ",
  tm: "TM",
  mn: "MN",
  kh: "KH",
  la: "LA",
  mm: "MM",
  bn: "BN",
  mo: "MO",
  fj: "FJ",
  pg: "PG",
  sb: "SB",
  vu: "VU",
  ws: "WS",
  to: "TO",
  ck: "CK",
  nu: "NU",
  pf: "PF",
  nc: "NC",
  re: "RE",
  gp: "GP",
  mq: "MQ",
  gf: "GF",
  pm: "PM",
  yt: "YT",
  tf: "TF",
  ax: "AX",
  fo: "FO",
  gl: "GL",
  gi: "GI",
  ad: "AD",
  mc: "MC",
  sm: "SM",
  va: "VA",
  li: "LI",
  al: "AL",
  ba: "BA",
  me: "ME",
  mk: "MK",
  rs: "RS",
  hr: "HR",
  si: "SI",
  bg: "BG",
  md: "MD",
  af: "AF",
  sy: "SY",
  ye: "YE",
  ly: "LY",
  sd: "SD",
  ss: "SS",
  so: "SO",
  dj: "DJ",
  er: "ER",
  rw: "RW",
  bi: "BI",
  mw: "MW",
  mg: "MG",
  sc: "SC",
  mv: "MV",
  bt: "BT",
  tl: "TL",
  pw: "PW",
  fm: "FM",
  mh: "MH",
  ki: "KI",
  nr: "NR",
  tv: "TV",
  as: "AS",
  gu: "GU",
  mp: "MP",
  pr: "PR",
  vi: "VI",
  vg: "VG",
  ky: "KY",
  bm: "BM",
  tc: "TC",
  ms: "MS",
  ai: "AI",
  ag: "AG",
  dm: "DM",
  gd: "GD",
  kn: "KN",
  lc: "LC",
  vc: "VC",
  cw: "CW",
  aw: "AW",
  sx: "SX",
  bq: "BQ",
  sr: "SR",
  gy: "GY",
  fk: "FK",
  gs: "GS",
  sh: "SH",
  io: "IO",
  ac: "AC",
  gg: "GG",
  je: "JE",
  im: "IM",
  eu: "EU",
};

/**
 * Infer country ISO from email domain TLD (e.g. user@company.co.in → IN).
 * Returns null for generic TLDs (.com, .org, .net) where country is ambiguous.
 */
export function detectCountryFromEmail(email: string): string | null {
  const trimmed = email.trim().toLowerCase();
  const at = trimmed.indexOf("@");
  if (at < 1) return null;

  const domain = trimmed.slice(at + 1);
  if (!domain.includes(".")) return null;

  const parts = domain.split(".").filter(Boolean);
  if (parts.length < 2) return null;

  const compound = parts.slice(-2).join(".");
  if (COMPOUND_TLD_TO_ISO[compound]) {
    return COMPOUND_TLD_TO_ISO[compound];
  }

  const single = parts[parts.length - 1];
  if (SINGLE_TLD_TO_ISO[single]) {
    return SINGLE_TLD_TO_ISO[single];
  }

  return null;
}
